approvedGitRepositories: []

defaultSemverRangePrefix: ""

enableScripts: false

enableTelemetry: false

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmPublishAccess: public

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "eslint-plugin-import@*":
    dependencies:
      typescript: "npm:@typescript/typescript6@6.0.2"
  "eslint-plugin-perfectionist@*":
    dependencies:
      typescript: "npm:@typescript/typescript6@6.0.2"
  "typescript-eslint@*":
    dependencies:
      typescript: "npm:@typescript/typescript6@6.0.2"

yarnPath: .yarn/releases/yarn-4.17.1.cjs
